plugins {
  id 'application'
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'com.oracle.database.jdbc:ojdbc11:23.4.0.24.05'
  implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
}

application {
  mainClass = 'com.silk.jdbcagent.Main'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

tasks.jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  manifest {
    attributes 'Main-Class': application.mainClass.get()
  }
  from {
    configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
  }
  archiveBaseName = 'jdbc-agent'
  archiveClassifier = 'all'
}
